### ISSUE TITLE
Node had an error: Unexpected op "ready" with data: [object Object]

### ISSUE THREAD

**Issue by Legendary4226** [SudhanPlayz/Discord-MusicBot#1209]
**Please describe the problem you are having in as much detail as possible:**
![image](https://user-images.githubusercontent.com/42912228/233850111-6e48ee6c-96b0-4aa7-9b1d-f0d9f41b6638.png)

### Essentials:
I have this error, the lavalink is "connected" but have a "problem".
My lavalink is fine and receive instructions from the bot (no errors from this side) :
![image](https://user-images.githubusercontent.com/42912228/233850338-aa3b71b6-ea79-4dec-bcf7-82da4e80863e.png)

And the bot crashes just because he already sent a reply :
![image](https://user-images.githubusercontent.com/42912228/233850382-c89e70f9-cbb2-4890-b2cd-c5eef73e9878.png)
![image](https://user-images.githubusercontent.com/42912228/233850398-34591479-c7cc-47cf-ad1d-7d36d2ed24f9.png)

I don't know if i'm clear.
I tried to just edit the code, delete all "❌ | Lavalink node is not connected" messages, but one persist and i can't find it.

- Bot Version: last + v4.1.2
- Commit Hash: i tried Master (e62292cf828e4f71e09c1d5710eb3f1da5fa632f) + release v4.1.2
- Node.js version: v17.9.1

#### Additional system info
- Docker (Pterodactyl)

**Comment by LewdHuTao** [comment]
1. refer this, its not an issue with our code https://github.com/freyacodes/Lavalink/issues/852
2. you get unknown interaction because your bot has bad connection, also why still use v4?
3. never edit the code if you dont know what youre doing, you may broke the bot

**Comment by lc787** [comment]
> 1. refer this, its not an issue with our code [Lavalink node has an error: Unexpected op "ready" with data: [object Object] freyacodes/Lavalink#852](https://github.com/freyacodes/Lavalink/issues/852)

The issue clearly states it's a client problem, the erela manager is unsupported.

**Comment by LewdHuTao** [comment]
> The issue clearly states it's a client problem, the erela manager is unsupported.

we’re not erela, tell erela.js maintainers to fix it (surely they not gonna fix it). this repo need to do a rewrite to another wrapper for sure as erela no longer support

**Comment by AndreP2211** [comment]
I got the problem fixed with the small change that I added 
            case "ready":
                this.sessionId = payload.sessionId
                break;
in "\node_modules\erela.js\dist\structures\Node.js"
In line 238

**Comment by Legendary4226** [comment]
Thank you @AndreP2211 ^^

@LewdHuTao Yeah it's not your code but now there is a "issue ticket" that show the problem for others. I have correctly setup everything and your code was "locked" to 'Lavalink not connected' (I updated to your V5, the issue persist !).
Maybe handle this "bug" of erela.js in your code to determine if the node is working or not. Because without more explanations I was facing an error without any lines of file information, and the bot was just not working, not my fault, not yours, but this issue is real.

Finally, to be clear of what I did (because I HATE when I read a post that find the solution without telling the solution xD ).
> I'm using the V5 of the bot (V4 have bugs I don't have the time to understand).
> I edited the file that Andre told me and everything works well ^^

**Comment by LewdHuTao** [comment]
> Thank you @AndreP2211 ^^
> 
> @LewdHuTao Yeah it's not your code but now there is a "issue ticket" that show the problem for others. I have correctly setup everything and your code was "locked" to 'Lavalink not connected' (I updated to your V5, the issue persist !). Maybe handle this "bug" of erela.js in your code to determine if the node is working or not. Because without more explanations I was facing an error without any lines of file information, and the bot was just not working, not my fault, not yours, but this issue is real.
> 
> Finally, to be clear of what I did (because I HATE when I read a post that find the solution without telling the solution xD ).
> 
> > I'm using the V5 of the bot (V4 have bugs I don't have the time to understand).
> > I edited the file that Andre told me and everything works well ^^

everything is already handled to show whether the lavalink is working or not lol. also why would we fix bug that not from us? 

"Maybe handle this "bug" of erela.js in your code to determine if the node is working or not."
so you tell us to fix this issue by editing the node_modules file? fyi editing node_modules files is not something you should do

**Comment by LewdHuTao** [comment]
anyway "Node had an error: Unexpected op "ready" with data: [object Object]" this is not even a bug its just a warning message lol, everyone who use erela.js wrapper have this issue

**Comment by phanhiep579x** [comment]
> I got the problem fixed with the small change that I added case "ready": this.sessionId = payload.sessionId break; in "\node_modules\erela.js\dist\structures\Node.js" In line 238

thanks!

**Comment by saher228** [comment]
> I got the problem fixed with the small change that I added case "ready": this.sessionId = payload.sessionId break; in "\node_modules\erela.js\dist\structures\Node.js" In line 238

Thank you very much helped out very much!!!

**Comment by saher228** [comment]
> **Please describe the problem you are having in as much detail as possible:** ![image](https://user-images.githubusercontent.com/42912228/233850111-6e48ee6c-96b0-4aa7-9b1d-f0d9f41b6638.png)
> 
> ### Essentials:
> I have this error, the lavalink is "connected" but have a "problem". My lavalink is fine and receive instructions from the bot (no errors from this side) : ![image](https://user-images.githubusercontent.com/42912228/233850338-aa3b71b6-ea79-4dec-bcf7-82da4e80863e.png)
> 
> And the bot crashes just because he already sent a reply : ![image](https://user-images.githubusercontent.com/42912228/233850382-c89e70f9-cbb2-4890-b2cd-c5eef73e9878.png) ![image](https://user-images.githubusercontent.com/42912228/233850398-34591479-c7cc-47cf-ad1d-7d36d2ed24f9.png)
> 
> I don't know if i'm clear. I tried to just edit the code, delete all "❌ | Lavalink node is not connected" messages, but one persist and i can't find it.
> 
> * Bot Version: last + v4.1.2
> * Commit Hash: i tried Master ([e62292c](https://github.com/SudhanPlayz/Discord-MusicBot/commit/e62292cf828e4f71e09c1d5710eb3f1da5fa632f)) + release v4.1.2
> * Node.js version: v17.9.1
> 
> #### Additional system info
> * Docker (Pterodactyl)

**You should also add "event" You should also add an event to fix all the errors with Lavalink**

 ```
case "ready":
                this.sessionId = payload.sessionId
                break;
                case "event":
                    this.sessionId = payload.sessionId
                    break;
in "\node_modules\erela.js\dist\structures\Node.js"
In line 238
```
fixes errors such as: 
 ```Lavalink: Node Main an error has occurred: Unexpected op "event" with data: [object Object] ```
and
``` Lavalink: Node Main an error has occurred: Unexpected op "ready" with data: [object Object]```
